### ISSUE TITLE
AttributeError: 'SentenceTransformerModel' object has no attribute 'encode

### ISSUE THREAD

**Issue by simonw** [simonw/llm-sentence-transformers#7]
```
% python -i $(which llm) sentence-transformers register \
  all-mpnet-base-v2 \
  --alias mpnet 
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/llm-sentence-transformers-kFV01F0q/bin/llm", line 33, in <module>
    sys.exit(load_entry_point('llm', 'console_scripts', 'llm')())
  File "/Users/simon/.local/share/virtualenvs/llm-sentence-transformers-kFV01F0q/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/llm-sentence-transformers-kFV01F0q/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/llm-sentence-transformers-kFV01F0q/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/llm-sentence-transformers-kFV01F0q/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/llm-sentence-transformers-kFV01F0q/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/llm-sentence-transformers-kFV01F0q/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/llm-sentence-transformers/llm_sentence_transformers.py", line 62, in register
    model.encode(["hello world"])
AttributeError: 'SentenceTransformerModel' object has no attribute 'encode'
>>> import pdb; pdb.pm()
> /Users/simon/Dropbox/Development/llm-sentence-transformers/llm_sentence_transformers.py(62)register()
-> model.encode(["hello world"])
```

**Comment by simonw** [comment]
I had to run this to test it:
```
rm ~/Library/Application\ Support/io.datasette.llm/sentence-transformers.json             
```
